development:
  adapter: postgresql
  database: nusgyms_dev
  pool: 5
  username: nusgyms
  password: <%= Rails.application.credentials.db[:password] %>

test:
  adapter: postgresql
  database: nusgyms_test
  pool: 5
  username: nusgyms
  password: <%= Rails.application.credentials.db[:password] %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5